<?php
$father_name_data= $block->getCustomer()->getCustomAttribute('father_name');
$father_name = $father_name_data ? $father_name_data->getValue() : null;

$mother_name_data= $block->getCustomer()->getCustomAttribute('mother_name');
$mother_name = $mother_name_data ? $mother_name_data->getValue() : null;


$configBlockObj= $block->getLayout()->createBlock('TrainingFurqan\CustomerAttribute\Block\CustomAttribute');

$is_enable_father_name = $configBlockObj->getConfigValue('customer/general/enable_father_name');
$is_enable_mother_name = $configBlockObj->getConfigValue('customer/general/enable_mother_name');
?>

<?php if($is_enable_father_name) { ?>
    <div class="field father name">
        <label class="label" for="father_name">
            <span><?= $block->escapeHtml(__("Father's Name")) ?></span>
        </label>
        <div class="control">
            <input type="text" name="father_name" id="father_name" value="<?=$block->escapeHtmlAttr($father_name);?>" title="<?= $block->escapeHtmlAttr(__("Father's Name")) ?>" class="input-text" >
        </div>
    </div>
<?php } ?>
<?php if($is_enable_mother_name) { ?>
    <div class="field mother name">
        <label class="label" for="mother_name">
            <span><?= $block->escapeHtml(__("Mother's Name")) ?></span>
        </label>
        <div class="control">
            <input type="text" name="mother_name" id="mother_name" value="<?=$block->escapeHtmlAttr($mother_name);?>" title="<?= $block->escapeHtmlAttr(__("Mother's Name")) ?>" class="input-text" >
        </div>
    </div>
<?php } ?>