<?php


/** @var $block \Magento\Catalog\Block\Product\View */
?>
<style>
    .size-selection {
        margin: 15px 0px;
    }
    .consulting-content {
        display: none;
    }
</style>
<div class="size-selection">
    <a href="#"><?php echo __('How to choose the right size?'); ?></a>
</div>
<div class="consulting-content" id="consulting-content">
    <!-- The codes below helps display a static block in the template phtml file-->
    <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('how-to-choose-the-right-size')->toHtml(); ?>
    <!-- We will create the block id how-to-choose-the-right-size in the backend later -->
</div>
<!-- You can learn How to use the Modal widget in the link https://devdocs.magento.com/guides/v2.2/javascript-dev-guide/widgets/widget_modal.html -->
<!-- The javascript codes below helps to display the popup content -->
<script>
    require([
        'jquery',
        'Magento_Ui/js/modal/modal'
    ], function($, modal) {
        // declaring initial options
        var options = {
            type: 'popup',
            responsive: true,
            innerScroll: true,
            title: '<?php echo __('How to choose the right size'); ?>'
        };
        // Initialize the modal widget to the consulting content
        var slide = modal(options, $('#consulting-content'));
        // Whenever click on the text link How to choose the right size?
        $('.size-selection a').on('click', function() {
            // open the popup content
            $('#consulting-content').modal('openModal');
            return false;
        });
    });
</script>